common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *common
  database: suppliers_rating_development
  username: postgres
  password: '123'

test:
  <<: *common
  database: suppliers_rating_test
  username: postgres
  password: '123'

production:
  <<: *common
  database: suppliers_rating_development
  username: postgres
  password: '123'
